version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /master/
      - approve_build_container:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /master/
      - aws-ecr/build-and-push-image:
          create-repo: false
          repo: test/app
          tag: 'latest,$CIRCLE_SHA1'